-- CreateEnum
CREATE TYPE "ServiceCategory" AS ENUM ('MAINTENANCE', 'PAINTING', 'HVAC', 'ELECTRICAL', 'PLUMBING');

-- CreateEnum
CREATE TYPE "ServiceSubcategory" AS ENUM ('LAWN_MOWING', 'GARDEN_CLEANUP', 'TREE_TRIMMING', 'PRESSURE_WASHING', 'INTERIOR_PAINTING', 'EXTERIOR_PAINTING', 'WALL_REPAIR', 'AC_INSTALLATION', 'AC_REPAIR', 'AC_MAINTENANCE', 'HEATING_INSTALLATION', 'OUTLET_INSTALLATION', 'LIGHTING_INSTALLATION', 'CIRCUIT_BREAKER', 'WIRING_REPAIR', 'LEAK_REPAIR', 'PIPE_INSTALLATION', 'DRAIN_CLEANING', 'FAUCET_INSTALLATION');

-- CreateEnum
CREATE TYPE "DifficultyLevel" AS ENUM ('EASY', 'MEDIUM', 'HARD', 'EXPERT');

-- AlterTable
ALTER TABLE "ServiceRequest" ADD COLUMN     "category" "ServiceCategory",
ADD COLUMN     "difficultyLevel" "DifficultyLevel" NOT NULL DEFAULT 'MEDIUM',
ADD COLUMN     "metadata" JSONB,
ADD COLUMN     "subcategory" "ServiceSubcategory";
